[tools]
# Stack
rust = "latest"

# Tools
opencode = "latest"
oxfmt = "latest"
cargo-binstall = "latest"
"cargo:watchexec-cli" = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["rust"] # Use rust-toolchain.toml

[tasks.test]
run = "cargo test --all-features"

[tasks."test:watch"]
run = "watchexec -e rs cargo test --all-features"

[tasks.format]
run = "cargo fmt --all"

[tasks.lint]
run = "cargo clippy --all-features -- -D warnings"

[tasks.ship]
run = "cargo publish --allow-dirty"